# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'spennyapp' do
  # Pods for spennyapp
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Functions', '~> 5.20.1'
  pod 'Firebase/DynamicLinks', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  # pod 'Firebase/Invites', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/RemoteConfig', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'Firebase/Performance', '~> 5.20.1'
  pod 'Fabric', '~> 1.9.0'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'FBSDKCoreKit', '~> 4.39.1'
  pod 'FBSDKLoginKit', '~> 4.39.1'
  pod 'FBSDKShareKit', '~> 4.39.1'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
   ]
   pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

   pod 'RNSVG', :path => '../node_modules/react-native-svg'

   post_install do |installer|
     installer.pods_project.targets.each do |target|
       if target.name == "React"
         target.remove_from_project
       end
     end
   end

end

target 'spennyapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spennyapp-tvOS

  target 'spennyapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
